// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1yWQCaWI1hv-wMjAcv1lF6A97JEjjP80',
    appId: '1:174601659060:web:c7eb2199749604c419ade1',
    messagingSenderId: '174601659060',
    projectId: 'shuaibi-followup-system',
    authDomain: 'shuaibi-followup-system.firebaseapp.com',
    storageBucket: 'shuaibi-followup-system.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh7U_yULpWeQ7MnV5sW6vR2E-fGpJnCvA',
    appId: '1:174601659060:ios:626299f8a724807819ade1',
    messagingSenderId: '174601659060',
    projectId: 'shuaibi-followup-system',
    storageBucket: 'shuaibi-followup-system.firebasestorage.app',
    iosBundleId: 'com.example.shuaibiFollowupSystem',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh7U_yULpWeQ7MnV5sW6vR2E-fGpJnCvA',
    appId: '1:174601659060:ios:626299f8a724807819ade1',
    messagingSenderId: '174601659060',
    projectId: 'shuaibi-followup-system',
    storageBucket: 'shuaibi-followup-system.firebasestorage.app',
    iosBundleId: 'com.example.shuaibiFollowupSystem',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATvjdGE1shzA0yvLFZXalBL_sJ6kCPoRs',
    appId: '1:174601659060:android:13ca9eb788e3b9ce19ade1',
    messagingSenderId: '174601659060',
    projectId: 'shuaibi-followup-system',
    storageBucket: 'shuaibi-followup-system.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1yWQCaWI1hv-wMjAcv1lF6A97JEjjP80',
    appId: '1:174601659060:web:86296415f2272c4e19ade1',
    messagingSenderId: '174601659060',
    projectId: 'shuaibi-followup-system',
    authDomain: 'shuaibi-followup-system.firebaseapp.com',
    storageBucket: 'shuaibi-followup-system.firebasestorage.app',
  );

}